### ISSUE TITLE
Not working with reverse proxy in specific directory

### ISSUE THREAD

**Issue by sandyboxy** [svenstaro/miniserve#1344]
Hello,
I've installed miniserve using the following `docker-compose.yml` file:
```yaml
version: "3.7"
 
services:
  miniserve:
    image: "docker.io/svenstaro/miniserve"
    container_name: "miniserve"
    ports:
      - "8000:8000"
    volumes:
      - ./tmp:/tmp
    #command: "-p 8889"
    environment:
      - MINISERVE_PATH=/tmp
      - MINISERVE_PORT=8000
      - MINISERVE_VERBOSE=true
      - ROUTE_PREFIX=/download
```

and this is my `nginx` conf:
```
server {
    listen       80;
    server_name  mydomain.tld;

    location /download {
        proxy_pass      http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

My intention is to serve miniserve on url `http://mydomain.tld/download/`.
Thanks for any help.
