### ISSUE TITLE
Assistance with Docker Compose

### ISSUE THREAD

**Issue by jmcombs** [svenstaro/miniserve#455]
I am using the miniserve Docker Image and was wondering how I can translate the flag and options for miniserve in my docker-compose file? For instance, toggling the `-D` flag and `-p` and `-t` options? Thank you.

**Comment by svenstaro** [comment]
You should be able to simply use the `command` section for that:
```
services:
  proxyboi:
    image: svenstaro/miniserve
    ports:
      - "8889:8889"
    volumes:
      - "/data:/data"
    command: "-p 8889 /data"
```
