### ISSUE TITLE
uploading area didn't show with mixed arguments '-vDFgHqruzWo'

### ISSUE THREAD

**Issue by Karmenzind** [svenstaro/miniserve#919]
After updating Docker Image from 0.19.2 to 0.22.0, uploading area and "Download .zip", which worked fine on 0.19.2, disappeared. 

![image](https://user-images.githubusercontent.com/17923071/192728171-c964e544-d24d-4fb5-a117-a72804dd8947.png)

Here is my configuration in docker-compose.yml:

```yaml
services:
  miniserve-host:
    image: svenstaro/miniserve:0.22.0
    restart: always
    ports: 
      - 0.0.0.0:8977:8080
    command: ' -p 8080 -vDFgHqruzWo  -t":)" /data'
    volumes:
      - /xxx:/data
      - /etc/localtime:/etc/localtime:ro
```

Then I tried using a single `-u` (the command line became `command: ' -p 8080 -u -vDFgHqrzWo  -t":)" /data'`) and the uploading and "Download .zip" worked again.
![image](https://user-images.githubusercontent.com/17923071/192728973-ad3d38a8-1480-4482-9dec-bc30c5912b86.png)
