### ISSUE TITLE
Error running Docker Container on ARM64

### ISSUE THREAD

**Issue by jmcombs** [svenstaro/miniserve#996]
I am attempting to run `miniserve` as a Docker container on Apple Silicone (M1 Pro). Works fine on an `x64` Mac but not on Apple Silicone. 

When I run, it crashes with `www exited with code 139` whether I use Docker Compose or from CLI.

```yaml
services:
  www:
    container_name: www
    image: svenstaro/miniserve
    #tty: true
    #restart: always
    volumes:
      - /www:/www
    ports:
      - "8080:8080"
    command: "--dirs-first --enable-tar --title www /www"
```

```sh
docker run -v /www:/www -p 8080:8080  -it docker.io/svenstaro/miniserve /www
```
